seed: 12341
trainer:
  init_args:
    use_time_code: false
    persist_ckpt: true
    log_directory: '/nvme/liyuanchun/rgeng'
    callbacks: ~
    training_strategy: ~
    num_epochs: 200
    ckpt_path: '/nvme/liyuanchun/dummy.ckpt'
data:
  name: cifar100_datamodule
  init_args:
    num_worker: 4
    batch_size: 128
    drop_last: false
    data_dir: ..
module:
  name: CIFARResNet
  init_args:
    depth: 56
    num_classes: 100
optimizer:
  name: SGD
  label_smoothing: 0.1
  reg_bn: false
  init_args:
    lr: 0.1
    weight_decay: 5e-5
    momentum: 0.9
lr_scheduler:
  name: MultiStepLR
  init_args:
    gamma: 0.1
    milestones:
      - 100
      - 150